[package]
name = "stl-rust"
version = "0.1.4"
edition = "2024"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module", "abi3-py38"] }

[profile.release]
opt-level = 3
lto = "fat"
strip = true
codegen-units = 1
